import Patient, { type IPatient } from "../db/models/Patient.model.js";
import iamServiceClient, { type IamUser } from "./iamService.client.js";

// Extended patient interface with user data
export interface IPatientWithUser extends Omit<IPatient, 'user_id'> {
  user_id: string;
  user?: IamUser | null; // Populated user data from IAM Service
}

export class PatientService {
  async createPatient(patientData: Partial<IPatient>): Promise<IPatient> {
    const patient = new Patient(patientData);
    return await patient.save();
  }

  async getAllPatients(
    filters: any = {},
    page: number = 1,
    limit: number = 10,
    populateUser: boolean = true // Option to populate user data
  ): Promise<{ patients: IPatientWithUser[]; total: number; page: number; totalPages: number }> {
    // Get all users from IAM Service first
    const allUsers = await iamServiceClient.getAllUsers();
    
    if (allUsers.length === 0) {
      return {
        patients: [],
        total: 0,
        page,
        totalPages: 0,
      };
    }

    // Sync: Create patient records for users that don't have one yet
    for (const user of allUsers) {
      const existingPatient = await Patient.findOne({ user_id: user._id }).lean();
      
      if (!existingPatient) {
        // Auto-create patient record for this user
        const newPatient = new Patient({
          user_id: user._id,
          patient_code: '', // Will be auto-generated by pre-save hook
          emergency_contact: {
            name: '',
            phone: '',
          },
          is_active: user.isActive,
          created_by: 'system',
        });
        
        await newPatient.save();
        console.log(`[Patient Service] Auto-created patient record for user ${user._id}`);
      }
    }

    // Now query patients with filters
    const skip = (page - 1) * limit;

    // Only select fields defined in the new schema
    const projection = {
      _id: 1,
      user_id: 1,
      patient_code: 1,
      emergency_contact: 1,
      last_visit_date: 1,
      last_test_type: 1,
      is_active: 1,
      created_at: 1,
      updated_at: 1,
      created_by: 1,
      is_deleted: 1,
      deleted_at: 1,
    };

    const [patients, total] = await Promise.all([
      Patient.find(filters, projection)
        .sort({ created_at: -1 })
        .skip(skip)
        .limit(limit)
        .lean(),
      Patient.countDocuments(filters),
    ]);

    let patientsWithUser: IPatientWithUser[] = patients as IPatientWithUser[];

    // Populate user data from IAM Service if requested
    if (populateUser && patients.length > 0) {
      // Create a map of users by ID for quick lookup
      const userMap = new Map(allUsers.map(user => [user._id, user]));

      patientsWithUser = patients.map((patient: any) => ({
        ...patient,
        user: patient.user_id ? userMap.get(patient.user_id) || null : null,
      }));
    }

    return {
      patients: patientsWithUser,
      total,
      page,
      totalPages: Math.ceil(total / limit),
    };
  }

  async getPatientById(id: string): Promise<IPatient | null> {
    return await Patient.findOne({ _id: id, isDeleted: false }).lean();
  }

  async getPatientByIdentityNumber(identityNumber: string): Promise<IPatient | null> {
    return await Patient.findOne({ identityNumber, isDeleted: false }).lean();
  }

  async getPatientByEmail(email: string): Promise<IPatient | null> {
    return await Patient.findOne({ email, isDeleted: false }).lean();
  }

  async updatePatient(id: string, updateData: Partial<IPatient>): Promise<IPatient | null> {
    return await Patient.findOneAndUpdate(
      { _id: id, isDeleted: false },
      { $set: updateData },
      { new: true, runValidators: true }
    ).lean();
  }

  async softDeletePatient(id: string, deletedBy: string): Promise<IPatient | null> {
    return await Patient.findOneAndUpdate(
      { _id: id, isDeleted: false },
      {
        $set: {
          isDeleted: true,
          deletedAt: new Date(),
          deletedBy,
        },
      },
      { new: true }
    ).lean();
  }

  async hardDeletePatient(id: string): Promise<boolean> {
    const result = await Patient.deleteOne({ _id: id });
    return result.deletedCount > 0;
  }

  async searchPatients(searchTerm: string, limit: number = 20): Promise<IPatient[]> {
    return await Patient.find({
      isDeleted: false,
      $or: [
        { fullName: { $regex: searchTerm, $options: "i" } },
        { identityNumber: { $regex: searchTerm, $options: "i" } },
        { email: { $regex: searchTerm, $options: "i" } },
        { phoneNumber: { $regex: searchTerm, $options: "i" } },
      ],
    })
      .limit(limit)
      .lean();
  }

  async getPatientStats(): Promise<any> {
    const [total, active, inactive, byGender, byBloodType] = await Promise.all([
      Patient.countDocuments({ isDeleted: false }),
      Patient.countDocuments({ isDeleted: false, isActive: true }),
      Patient.countDocuments({ isDeleted: false, isActive: false }),
      Patient.aggregate([
        { $match: { isDeleted: false } },
        { $group: { _id: "$gender", count: { $sum: 1 } } },
      ]),
      Patient.aggregate([
        { $match: { isDeleted: false, bloodType: { $exists: true, $ne: "" } } },
        { $group: { _id: "$bloodType", count: { $sum: 1 } } },
      ]),
    ]);

    return {
      total,
      active,
      inactive,
      byGender,
      byBloodType,
    };
  }
}
