// ============================================
// EVENT CODES CONSTANTS
// Based on Section 2.8 Event Table
// ============================================

export const EVENT_CODES = {
  TEST_ORDER_CREATED: 'E_00001',
  TEST_ORDER_UPDATED: 'E_00002',
  TEST_ORDER_DELETED: 'E_00003',
  TEST_RESULT_MODIFIED: 'E_00004',
  COMMENT_ADDED: 'E_00005',
  COMMENT_MODIFIED: 'E_00006',
  COMMENT_DELETED: 'E_00007',
  REVIEW_COMPLETED: 'E_00008',
  INSTRUMENT_STATUS_CHANGED: 'E_00009',
  USER_STATUS_CHANGED: 'E_00010',
} as const;

export const EVENT_CATEGORIES = {
  TEST_ORDER: 'TEST_ORDER',
  TEST_RESULT: 'TEST_RESULT',
  COMMENT: 'COMMENT',
  REVIEW: 'REVIEW',
  INSTRUMENT: 'INSTRUMENT',
  USER: 'USER',
  REAGENT: 'REAGENT',
  SYSTEM: 'SYSTEM',
} as const;

export const SERVICE_NAMES = {
  IAM: 'IAM',
  PATIENT: 'PATIENT',
  TEST_ORDER: 'TEST_ORDER',
  WAREHOUSE: 'WAREHOUSE',
  INSTRUMENT: 'INSTRUMENT',
  MONITORING: 'MONITORING',
} as const;

export const EVENT_ACTIONS = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  REVIEW: 'REVIEW',
  ACTIVATE: 'ACTIVATE',
  DEACTIVATE: 'DEACTIVATE',
  LOCK: 'LOCK',
  UNLOCK: 'UNLOCK',
} as const;
